### ISSUE TITLE
Use of options with beef modules

### ISSUE THREAD

**Issue by ghost** [byt3bl33d3r/BeEF-API#1]
Is there a way of setting options for a module?

**Comment by byt3bl33d3r** [comment]
@GeorgeTheobald hi,
Yes as you can see here https://github.com/byt3bl33d3r/BeEF-API/blob/master/beefapi.py#L236 , the run() function accepts an options parameter to which you pass a JSON object containing the module options

**Comment by ghost** [comment]
@byt3bl33d3r  Thank you for your help.
